### PR TITLE
Add go plugin + Kanagawa theme (Light Mode, Dark Mode)

### PR DESCRIPTION
**Pull request by zSnails**
Pretty much what the title says, let me know if I missed anything

### CODE REVIEW

**Comment by zSnails** [comment]
I was going to add the plugin and both themes in their own pull request, but things happened, and I ended up uploading the dark theme to this branch as well, oh well

**Review by face-hh — CHANGES_REQUESTED** [review]
"inteface" should be "interface" instead

**Comment by Symmettry** [comment]
to_list function is useless. Just table.insert(table, match) instead of table[match] = match

**Comment by zSnails** [comment]
@Symmettry I did that to avoid repeating function and variable names on the autocomplete menu

**Comment by Symmettry** [comment]
Just check if the list doesn’t have it?

**Comment by zSnails** [comment]
@Symmettry well you could do it that way, although that'd be a bit slow wouldn't it? :^), checking if the list doesn't have it will be O(n), with this method it's always O(1), and yes, I know that this is just a toy editor and that no one's using this for actual coding, just stating why I did it, I'll change it

**Comment by Symmettry** [comment]
Or you could also ignore it anyway. I feel it might be better if GriddyCode itself dealt with repeats.

**Comment by zSnails** [comment]
Yeah that'd be a lot better, but having the same name show up 7 times in the autocomplete menu is kinda whack, I could open another pr and implement that

**Review by face-hh — APPROVED** [review]

**Pull request merged**
