### PR TITLE
Create html.lua

### PR DESCRIPTION
**Pull request by elefantapan**

### CODE REVIEW

**Comment by face-hh** [comment]
I don't really like the comments, I think they should be changed.

Good job on adding every keyword though - looks nice :)

**Comment by elefantapan** [comment]
I'm not good with making comments

**Comment by Corne2Plum3** [comment]
I think you should add this line to support comments in HTML
```lua
highlight_region("<!--", "-->", "comments", false)
```

**Comment by elefantapan** [comment]
Anyone here good at making comments? I need help to make HTML comments

**Comment by uynilo9** [comment]
> I think you should add this line to support comments in HTML
> 
> ```lua
> highlight_region("", "comments", false)
> ```

btw you don't need the fourth argument bc it's set to false by default

**Comment by Assassin-1234** [comment]
> Anyone here good at making comments? I need help to make HTML comments

let me try and help lol

- HTML more like hyper text MID language LMFAO
- please for the love of god use reactjs instead
- they speak HTML in mexico. HOT TAMALES for MY LADIES  🥁💃🪕🕺🥁💃🪕🫔🫔🫔

**Comment by uynilo9** [comment]
> Anyone here good at making comments? I need help to make HTML comments

HTML is not a real programming language

**Pull request merged**
