### PR TITLE
C# language support

### LINKED ISSUE #53: c# lang
Please, add c# lang
thanks 😉

### PR DESCRIPTION
**Pull request by RealPacket**
# C# language support

Added C# support.

## Checklist

- [X] Auto complete (detect_functions and detect_variables)
- [X] Comments (not sure if they're good though)
- [X] Syntax highlighting (most of the code was generated by [MonarchToGriddyPlug](https://github.com/RealPacket/MonarchToGriddyPlug))

## Additional Info

Fixes #53

### CODE REVIEW

**Comment by ItsTato** [comment]
A. Wow, ok then I guess
My cs.lua is still incomplete as well (my braincells were unable to figure out a detect functions/detect variables functions) so I guess I'll just upload it here just in case?

Note: Zipped becuase github doesn't like .lua files in PR comments..
[cs.lua.zip](https://github.com/face-hh/griddycode/files/14749473/cs.lua.zip)

**Comment by RealPacket** [comment]
> A. Wow, ok then I guess My cs.lua is still incomplete as well (my braincells were unable to figure out a detect functions/detect variables functions) so I guess I'll just upload it here just in case?
> 
> Note: Zipped becuase github doesn't like .lua files in PR comments.. [cs.lua.zip](https://github.com/face-hh/griddycode/files/14749473/cs.lua.zip)

Look at the difference between the variable declaration and assignment syntax,
you'll see there's 2 words for the declaration and 1 for the assignment,
so make the regex match those 2 words, split it by the spaces, and index to the relevant part.

Use a Lua pattern viewer (i.e. [this one](https://gitspartv.github.io/lua-patterns/)) and a Lua pattern tester (i.e. [this one](https://montymahato.github.io/lua-pattern-tester/))

**Comment by RealPacket** [comment]
The reason why this is still marked as a draft is because the variable and function auto complete seem to not work on 1.1.1. I need to test.

**Comment by ItsTato** [comment]
I tried many patterns but just couldn't get it to work, so I'm just leaving this on to ya :3

**Comment by RealPacket** [comment]
Just found out that detect_functions doesn't work on Lua 5.4 because match:split DOESN'T EXIST??? And `match` is a string...
image

**Comment by RealPacket** [comment]
Lua doesn't even have string.split???

**Comment by Symmettry** [comment]
splitstr()

**Comment by ItsTato** [comment]
no lol, our bussin overlord gave us a splitstr() func tho

**Comment by RealPacket** [comment]
Ok, I've made a polyfill so that it works on garbage Lua 5.4, I'm going to commit it now.

**Comment by RealPacket** [comment]
> no lol, our bussin overlord gave us a splitstr() func tho

imagine using a language but you have to provide a splitstr function because the language you're using doesn't have a built in split function 💀

**Comment by RealPacket** [comment]
tested it, works :shipit:.
image

**Comment by RealPacket** [comment]
anyways, I need to fix the pattern, it will only work if the type and name are letters.

**Comment by RealPacket** [comment]
I didn't fix it, but I added @-variable support, actual fix should be worked on now.

**Comment by RealPacket** [comment]
> I didn't fix it, but I added @-variable support, actual fix should be worked on now.

image

**Comment by RealPacket** [comment]
I'd say that this is done. Anything else can be a review and I can edit it until we're ready.

**Comment by RealPacket** [comment]
I finally open sourced my Monarch language to GriddyCode plugin! Here: <https://github.com/RealPacket/MonarchToGriddyPlug>

**Comment by face-hh** [comment]
LGTM

**Pull request merged**
