### PR TITLE
Fix file_manager trying to run a non-existant command on the gaming OS (Michaelsoft Binbows)

### LINKED ISSUE #68: "pwd" error on gaming OS 10 (Windows 10)
**Describe the bug**
GriddyCode's File manager tries to run `pwd` on Windows, however, `pwd` doesn't exist.
https://github.com/face-hh/griddycode/blob/dff8167af5909637d7aba158ae442729055683a2/Scripts/file_manager.gd#L31
#67 Fixes this issue.

**To Reproduce**
Run GriddyCode
Check logs, it should mention "ERROR: Could not create child process: pwd", otherwise, you're not using Windows.

**Expected behavior**

**Screenshots**
Error:
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1.1.1

### PR DESCRIPTION
**Pull request by RealPacket**
Why does the gayming OS have to break everything!!!
Fixes #68

### CODE REVIEW

**Comment by ItsTato** [comment]
This is a certified gayming OS win

**Comment by RealPacket** [comment]
> This is a certified gayming OS win

You WILL run a proprietary OS that steals all of your info and reports to the FBI and NSA
You WILL be governed as if this OS was a communist country
You WILL keep Microsoft Edge installed at all times because we want you to
You WILL be forced to have a TPM because we need better DRM (Digital Rights Management) so we can be even more better at communism on your OWN device

**Comment by ItsTato** [comment]
all of these are absolute W
1) i get to be famous
2) im communist 
3) another browser to multi account with
4) i use windows 10 windows 11 sucks ew boo windows 11 grr

i only use my linux laptop when things like this amazing code editor appearf

**Comment by Symmettry** [comment]
> all of these are absolute W
> 
> 1. i get to be famous
> 2. im communist
> 3. another browser to multi account with
> 4. i use windows 10 windows 11 sucks ew boo windows 11 grr
> 
> i only use my linux laptop when things like this amazing code editor appear

wtf based

**Comment by zSnails** [comment]
This is a certified michaelsoft binbows classic

**Comment by RealPacket** [comment]
Added an issue hopefully to get merged quicker

**Pull request merged**
