### PR TITLE
Add Catppuccin themes to GC

### PR DESCRIPTION
**Pull request by uynilo9**
pls review these themes thx <3

### CODE REVIEW

**Comment by ItsTato** [comment]
I love these!
They're all very nice on the eyes.

When I try to select Latte I get a white screen though.
I'm not sure if this is only happening to me or to someone else as well?

**Comment by face-hh** [comment]
> I love these! They're all very nice on the eyes.
> 
> When I try to select Latte I get a white screen though. I'm not sure if this is only happening to me or to someone else as well?

Try disabling glow in the settings

P.S. will check these out in a few hours

**Comment by ItsTato** [comment]
Thanks!

The background shouldn't be #ffffff though..

Screenshot_5

**Comment by ItsTato** [comment]
Hey, not very sure on how much this is related but still a very interesting fact is that Frappe (the whitescreener) is the only theme that doesn't use hexadecimal values with letters in them for some of its values..

Also, the values that get messed up (after turning off the glow) are really only the ones that don't have letters in them. All other colors did apply correctly.

**Comment by uynilo9** [comment]
> Thanks!
> 
> The background shouldn't be #ffffff though..
> 
> Screenshot_1
> 
> Edit: uploaded wrong screenshot, oof.

honestly it's #eff1f5
and who uses light theme when programming lmao

**Comment by ItsTato** [comment]
> honestly it's #eff1f5 and who uses light theme when programming lmao

apologies! I didn't check with a color picker.

Also, I use dark themes to program.

**Comment by Blackneeed** [comment]
No way, someone made this for gc.

**Pull request merged**
