### PR TITLE
Add user zoom controls

### PR DESCRIPTION
**Pull request by MinecraftPublisher**
`Ctrl +` and `Ctrl ]` for zooming in
`Ctrl -` and `Ctrl [` for zooming out

Very simple

### CODE REVIEW

**Review by ItsTato — COMMENTED** [review]
Why did bro leave in a macOS preset :skull:

**Comment by MinecraftPublisher** [comment]
Because I'm exporting on MacOS?? duh

**Comment by MinecraftPublisher** [comment]
Also for future use

**Comment by face-hh** [comment]
Try adding the action through the g
Godot editor instead of hardcoding them. Go to Project > Project Settings > Input Map.

Also, no macOS preset, and why change the shake strength from 15 to 10?

**Comment by MinecraftPublisher** [comment]
mb. i forgot to change the shake strength back. you could also remove the macos preset if you want

**Comment by MinecraftPublisher** [comment]
also it'd be VERY NICE if you said this an hour ago, before i hardcoded them

**Comment by face-hh** [comment]
Closing because it goes against Griddycode's goal

**Pull request closed without merging**
